// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoqbvocwupqamuodogyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcWJ2b2N3dXBxYW11b2RvZ3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzUzOTAsImV4cCI6MjA3MDI1MTM5MH0.CMD1l3ik8iXWhjzXDQdkC_mFLNtxJa5BZ2CMtmnLWTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});